### ISSUE TITLE
Give a warning for non-ShellJS flags

### ISSUE THREAD

**Issue by nfischer** [nfischer/shelljs-transpiler#10]
If the user types in flags that bash (probably) supports, but ShellJS doesn't, it would be good to check this and give a warning.

**Comment by Schmavery** [comment]
Was this fixed by https://github.com/nfischer/shelljs-transpiler/commit/05a1dfa9c0e773a608bb74adb8a0631bd37e512d?

**Comment by nfischer** [comment]
Ah yes, I believe so. Thanks for pointing this out!
